### ISSUE TITLE
Issue adding a new route to login page

### ISSUE THREAD

**Issue by RaedMou** [BilalBouk/reactstrap-basic-sidebar#7]
Hi, 

I'm trying to add a new page "/" for login and I made a main.js containing the Content and the SideBar so my App looks like this : 

```
<Router>
      <Switch>
        <Route exact path="/" component={Login} />
        <Route exact path="/home" component={Main} />
      </Switch>
    </Router>
```

When I navigate in the app it works, but when I reload a page , for example "/home/faq" it show a blank page, what can I do please ?

Thanks

**Comment by RaedMou** [comment]
Hi, Can you please send me your email ?

**Comment by BilalBouk** [comment]
hi, sorry for the delay
i think you're getting a blank page because there is no route match in the switch component.
note that when we pass the exact props to a route component it forces a full match in your case `/home/faq` which doesn't exists.
i guess you're using nested routes so to fix that you should either remove the exact props or use a wildcard  matching on the home route
`<Route path="/home" component={Main} />`
or
`<Route exact path="/home/*" component={Main} />`

**Comment by RaedMou** [comment]
Hi, Can you please send me your email ?

**Comment by BilalBouk** [comment]
dust.long00@gmail.com
